trigger:
- main

variables:
- group: 'CommonVariables'
- name: newResourceGroupName
  value: 'ENTER-RG-NAME-HERE'

pool:
  vmImage: 'windows-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azureconnection'
    subscriptionId: '1aa42b20-3482-4a30-bbed-c82350c97417'
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(newResourceGroupName)
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'environment/armtemplate/template.json'
    csmParametersFile: 'environment/armtemplate/params.json'
    deploymentMode: 'Incremental'

